book <- read.csv("C:/Users/USER/Downloads/assignment sets/assoication rules/book (1).csv",header=T,colClasses = "factor")
View(book)
str(book)
class(book)
book_data <- as(as.matrix(book),"transactions")
library(arules)
rule <- apriori(book)
summary(rule)
rule3 <- apriori(book,parameter=list(minlen=2,maxlen=3,support=0.5))
inspect(rule3)
r1 <- inspect(head(sort(rule3,by="lift")))

rule4 <- apriori(book,parameter=list(minlen=4,maxlen=8,support=0.6))
inspect(rule4)
r1 <- inspect(head(sort(rule4,by="lift")))

rule5 <- apriori(book,parameter=list(minlen=2,maxlen=3,support=0.7))
inspect(rule5)
r1 <- inspect(head(sort(rule5,by="lift")))
